<?php
// Initialize the session
session_start();

// Include config file
require_once "config.php";
require_once "vendor/restdbclass.php";
require_once "vendor/autoload.php";
require_once "vendor/function.php";
// Cloudinary
require 'vendor/cloudinary/cloudinary_php/src/Cloudinary.php';
require 'vendor/cloudinary/cloudinary_php/src/Uploader.php';
require 'vendor/cloudinary/cloudinary_php/src/Api.php';

$collectionName = "friend";
$obj =   ' {
    "rank": "พ.ท.",
    "name": "ปัณณรุจน์",
    "lastname": "เกียรติธนโยธิน",
    "position": "ผบ.ป.2 พัน.2 รอ.",
    "province": "ปราจีนบุรี",
    "Email": "yeeomsin4051@gmail.com",
    "telephone": "0815587589",
    "LineID": "chaiyee40",
    "nickname": "",
    "detail": "ไฉ่ยี่ พล.ร.2 ทภ.1"
  },
  {
    "rank": "พ.ท.",
    "name": "หม่ำ",
    "lastname": "โคราช",
    "position": "นักทดสอบระบบ",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0987656787",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "พูลศักดิ์",
    "lastname": "พรประเสริฐ",
    "position": "ผบ.ขกท.กองพล",
    "province": "อื่นๆ",
    "Email": "Phoolsak@gmail.com",
    "telephone": "0899265797",
    "LineID": "Phoolsakp",
    "nickname": "",
    "detail": "ต้น เฉือน ดำ ขกท ส่วนกลาง"
  },
  {
    "rank": "พ.ท.",
    "name": "สนิท",
    "lastname": "หอมหวล",
    "position": "ผบ.ส.พัน.3 พล.ร.3",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0855649559",
    "LineID": "",
    "nickname": "",
    "detail": "หนิด เครา พล.ร.3 ทภ.2"
  },
  {
    "rank": "พ.อ.",
    "name": "กฤษ",
    "lastname": "โชติจิระมานนท์",
    "position": "ผช.ผอ.กผสป.พธ.ทบ.",
    "province": "นนทบุรี",
    "Email": "krit405192@gmail.com",
    "telephone": "0939459426",
    "LineID": "กฤษ",
    "nickname": "",
    "detail": "เกย์ กฤษ จอห์น พธ.ทบ. ส่วนกลาง"
  },
  {
    "rank": "พ.ท.",
    "name": "จิระกิจ",
    "lastname": "จิตรภักดี",
    "position": "ผบ.ร.16 พัน.1",
    "province": "ร้อยเอ็ด",
    "Email": "Befirst4051@gmail.com",
    "telephone": "0860989811",
    "LineID": "",
    "nickname": "",
    "detail": "ยายชา กล้วยแขก พล.ร.6 ทภ.2"
  },
  {
    "rank": "พ.ท.",
    "name": "เจตนา",
    "lastname": "ไชยถาวร",
    "position": "รอง หก.กยก.มทบ.37",
    "province": "เชียงราย",
    "Email": "jatetana@gmail.com",
    "telephone": "0905166055",
    "LineID": "par_jate",
    "nickname": "",
    "detail": "เค มทบ.37 ทภ.3"
  },
  {
    "rank": "พ.ท.",
    "name": "วีระชาติ",
    "lastname": "โชติวรอานนท์",
    "position": "ผบ.พัน.พัฒนา ๓",
    "province": "เชียงใหม่",
    "Email": "Weerachat4051@hotmail.com",
    "telephone": "0813819191",
    "LineID": 813819191,
    "nickname": "",
    "detail": "กิ่ง ทภ.3"
  },
  {
    "rank": "พ.ท.",
    "name": "ชุติกร",
    "lastname": "ชุมคง",
    "position": "รอง หน.กกพ.มทบ.๔๖",
    "province": "ปัตตานี",
    "Email": "chutigorn2mayk@gmail.com",
    "telephone": "0892875657",
    "LineID": "mayk40",
    "nickname": "",
    "detail": "เมย์ ทภ.4"
  },
  {
    "rank": "พ.ท.",
    "name": "พงศ์พิณชาญ",
    "lastname": "สุขเสียงศรี",
    "position": "หน.ผปก.วสท.",
    "province": "กรุงเทพมหานคร",
    "Email": "",
    "telephone": "0871049669",
    "LineID": "",
    "nickname": "",
    "detail": "โหน่ง"
  },
  {
    "rank": "พ.ท.",
    "name": "สมภพ",
    "lastname": "นิลแนบแก้ว",
    "position": "ผบ.รพศ.2 พัน.1",
    "province": "ลพบุรี",
    "Email": "s.ninnabkaew@hotmail.com",
    "telephone": "0818584051",
    "LineID": "Commanderchicken",
    "nickname": "",
    "detail": "ไก่ รบพิเศษ รพศ."
  },
  {
    "rank": "พ.ท.",
    "name": "ทัตตเดช",
    "lastname": "สุวรรณรัตน์",
    "position": "ผบ.ป.5 พัน.105",
    "province": "นครศรีธรรมราช",
    "Email": "sitt1_51@hotmail.com",
    "telephone": "0841990222",
    "LineID": "Tattadet",
    "nickname": "",
    "detail": "พล.ร.5 ทภ.4"
  },
  {
    "rank": "พ.ท.",
    "name": "นรเศรษฐ์",
    "lastname": "มุนีรักษา",
    "position": "ผบ.พัน.นร.รร.ขส.ขส.ทบ.",
    "province": "นนทบุรี",
    "Email": "simon.muniraksa@gmail.com",
    "telephone": "0863885206",
    "LineID": "simon4051",
    "nickname": "",
    "detail": "ม่อน"
  },
  {
    "rank": "พ.ท.",
    "name": "รัชชพงษ์",
    "lastname": "รัตนบัญญติ",
    "position": "ผบ.ร.31 พัน.1 รอ.",
    "province": "ลพบุรี",
    "Email": "fluke40@hotmail.com",
    "telephone": "0817347833",
    "LineID": "fluke4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วสุธา",
    "lastname": "ฤกษ์จำนงค์",
    "position": "รอง หก.กบร.บชร.2",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0956164774",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ธรรมนันท์",
    "lastname": "บุญธรรม",
    "position": "อจ.รร.สธ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "",
    "telephone": "0859891300",
    "LineID": "nonnie2722",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "อนุศักดิ์",
    "lastname": "ทวีพร้อม",
    "position": "ราชการบำนาญ",
    "province": "สุรินทร์",
    "Email": "Sapza_ton@hotmail.com",
    "telephone": "0818878728",
    "LineID": "Nudesh",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "เรวัตร",
    "lastname": "เซ่งเข็ม",
    "position": "รอง เสธ ร.15",
    "province": "นครศรีธรรมราช",
    "Email": "Rewat4051@gmail.com",
    "telephone": "0894623251",
    "LineID": "ray4051",
    "nickname": "",
    "detail": "ง่าม"
  },
  {
    "rank": "พ.ท.",
    "name": "กิตติภพ",
    "lastname": "ศรีเมือง",
    "position": "ผช.ฝอ.5 ทภ.1",
    "province": "กรุงเทพมหานคร",
    "Email": "srimuang40@hotmail.com",
    "telephone": "0842172633",
    "LineID": "sir.o4056",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ปรัชญา",
    "lastname": "หล้าวิเศษ",
    "position": "ผบ.ร.6 พัน.1",
    "province": "อุบลราชธานี",
    "Email": "lawiset_crma51@hotmail.com",
    "telephone": "0897184333",
    "LineID": 1427100928,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "อภิรักษ์",
    "lastname": "แสงกระสินธ์",
    "position": "อจ.สกศ.รร.จปร.",
    "province": "นครนายก",
    "Email": "s.apiruk4051@gmail.com",
    "telephone": "0841216162",
    "LineID": "apiruk_4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วิชญ์วิสิทธ์",
    "lastname": "เทียมจิตร",
    "position": "รอง.ผบ.พัน.สบร.๒๒ บชร.๒",
    "province": "นครราชสีมา",
    "Email": "bom4051@gmail.com",
    "telephone": "0831098844",
    "LineID": "Suicidebom",
    "nickname": "",
    "detail": "หม่ำ"
  },
  {
    "rank": "พ.อ.",
    "name": "สมดุลย์",
    "lastname": "ศิลป์เจริญ",
    "position": "รอง ผอ.กนผ.พท.ศอพท.",
    "province": "กรุงเทพมหานคร",
    "Email": "Silcharoen@hotmail.com",
    "telephone": "0656745058",
    "LineID": "Somduls",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "พิเชษฐ",
    "lastname": "ดาศรี",
    "position": "ผบ.ม.7 พัน.14",
    "province": "ขอนแก่น",
    "Email": "Archa6142@gmail.com",
    "telephone": "0993536936",
    "LineID": "Archa6142",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "รัชพล",
    "lastname": "อุ้มเงิน",
    "position": "ผช.ฝยก.ทภ.2",
    "province": "นครราชสีมา",
    "Email": "ohm_cowboy@hotmail.com",
    "telephone": "0646659498",
    "LineID": "40ohm",
    "nickname": "",
    "detail": "โอห์ม"
  },
  {
    "rank": "พ.อ.",
    "name": "เอกรักษ์",
    "lastname": "สิงหพงษ์",
    "position": "รอง ผอ.กกพ.นทพ.",
    "province": "กรุงเทพมหานคร",
    "Email": "ekkaruck.s@hotmail.com",
    "telephone": "0895533537",
    "LineID": "Noom4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ภคพล มีทิพย์",
    "lastname": "",
    "position": "เสธ.ร.6",
    "province": "อุบลราชธานี",
    "Email": "pakaphon.boo@gmail.com",
    "telephone": "0898493841",
    "LineID": "boo4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "เจนยุทธ์",
    "lastname": "สาดี",
    "position": "หก.กขว.มทบ.29",
    "province": "สกลนคร",
    "Email": "Genyut@gmail.com",
    "telephone": "0994964969",
    "LineID": "Lovepupe",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ธเนศ",
    "lastname": "พงศ์วิพัฒน์",
    "position": "รอง ผบ.พัน.สห.11",
    "province": "กรุงเทพมหานคร",
    "Email": "Thanetmp51@gmail.com",
    "telephone": "0910246110",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ประจักษ์",
    "lastname": "ระลึก",
    "position": "ผบ.ร.29 พัน.3",
    "province": "กาญจนบุรี",
    "Email": "Prajsk292@gmail.com",
    "telephone": "0899219668",
    "LineID": 899219668,
    "nickname": "",
    "detail": "จึก"
  },
  {
    "rank": "พ.อ.",
    "name": "เปรม",
    "lastname": "ไทยสุชาติ",
    "position": "รอง ผบ.นพค.55",
    "province": "นครราชสีมา",
    "Email": "unn01@hotmail.com",
    "telephone": "0819677258",
    "LineID": "sudteencod",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "วุฒิศักดิ์",
    "lastname": "สุขยฤกษ์",
    "position": "ผช.ผอ.กคช.กช.",
    "province": "ราชบุรี",
    "Email": "woody4051@gmail.com",
    "telephone": "0835848514",
    "LineID": "wut4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ภุชงค์",
    "lastname": "ลีติรัตน์นัยน์",
    "position": "ผบ.ป.72 พัน.723",
    "province": "ลพบุรี",
    "Email": "Puchong1234@hotmail.com",
    "telephone": "0894467776",
    "LineID": "puchong40",
    "nickname": "",
    "detail": "ชง"
  },
  {
    "rank": "พ.ท.",
    "name": "จิรจำนงค์",
    "lastname": "โกษาวัง",
    "position": "ผบ.ม.พัน.27พล.ม.2รอ.",
    "province": "สระบุรี",
    "Email": "Jigs33@hotmail.com",
    "telephone": "0835961661",
    "LineID": "Jirachumnong",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "จีรวิทย์ เผือดผุด",
    "lastname": "",
    "position": "ผบ.ป.6 พัน.23",
    "province": "นครราชสีมา",
    "Email": "Jeerawit4051@gmail.com",
    "telephone": "0818134051",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "เจษฎา",
    "lastname": "แก้วษา",
    "position": "รอง ผอ.กบ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "Jedsada.k51@gmail.com",
    "telephone": "0857235199",
    "LineID": "",
    "nickname": "",
    "detail": "แป๊ะ"
  },
  {
    "rank": "พ.อ.",
    "name": "ธนัญชัย",
    "lastname": "ดีประเสริฐ",
    "position": "นฝป.ทภ.4 /ชรก. หน.ผบค.สบค.กอ.รมน.ภาค 4 สน.",
    "province": "ยะลา",
    "Email": "Arndy4051@gmail.com",
    "telephone": "0870984924",
    "LineID": "Arndycrma51",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ภาณุวัฒน์",
    "lastname": "สุคชเดช",
    "position": "เสธ.ร.25",
    "province": "ระนอง",
    "Email": "panuwat4051@gmail.com",
    "telephone": "0890225328",
    "LineID": "panuwat4051",
    "nickname": "",
    "detail": "มืด ดำ"
  },
  {
    "rank": "พ.ท.",
    "name": "พัทธดนย์",
    "lastname": "สัมมาโพธิ์",
    "position": "ผบ.ส.พัน.6 พล.ร.6",
    "province": "ร้อยเอ็ด",
    "Email": "chae4051@gmail.com",
    "telephone": "0868659732",
    "LineID": "chae4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "คณิต",
    "lastname": "คหบดีกนกุล",
    "position": "ผบ.รศ.ขกท.สน.จชต.",
    "province": "ยะลา",
    "Email": "kanit4051@hotmail.com",
    "telephone": "0915351562",
    "LineID": "kanit4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "รณรงค์",
    "lastname": "เส็งมี",
    "position": "ผบ.กรม ทพ.13",
    "province": "สระแก้ว",
    "Email": "battalion.11@hotmail.com",
    "telephone": "0804656535",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ธนนาถ",
    "lastname": "คล่องเชิงสาน",
    "position": "ฝ่ายนโยบายและแผน สทป.",
    "province": "กรุงเทพมหานคร",
    "Email": "thananart.k@dti.or.th",
    "telephone": "0835354145",
    "LineID": "",
    "nickname": "",
    "detail": "โน๊ต ถ่อย"
  },
  {
    "rank": "พ.ท.",
    "name": "ศักรินทร์",
    "lastname": "ตาแก้ว",
    "position": "ผบ.ขกท.กกล.ผาเมือง",
    "province": "เชียงใหม่",
    "Email": "keng-yok@hotmail.com",
    "telephone": "0882615916",
    "LineID": "Sonic4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "บัญชาชิต",
    "lastname": "แสนสุนนท์",
    "position": "รอง ผอ. กอง ขว.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "banchachit@gmail.com",
    "telephone": "0996146154",
    "LineID": "banchachit03",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "จุลพงษ์",
    "lastname": "เดชกล้า",
    "position": "ผช.ผอ.กกพ.นทพ.",
    "province": "กรุงเทพมหานคร",
    "Email": "Chul4051@gmail.com",
    "telephone": "0864696658",
    "LineID": "Chulapong4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ชัยกฤต",
    "lastname": "ชรารัตน์",
    "position": "ผบ.นร.รร.การบิน ทบ.",
    "province": "ลพบุรี",
    "Email": "Cadettui@yahoo.com",
    "telephone": "0959298782",
    "LineID": 993292425,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สมยงค์",
    "lastname": "เมืองพิล",
    "position": "ผบ.หน่วย ขกท.กองพล",
    "province": "นครศรีธรรมราช",
    "Email": "amic4051@gmail.con",
    "telephone": "0824355641",
    "LineID": "ny4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ธารนรินทร์",
    "lastname": "บำรุงภักดี",
    "position": "รอง ผบ.กรม ทพ.21",
    "province": "เลย",
    "Email": "tbarungphakdi@ gmail.com",
    "telephone": "0870809459",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ชวอรรถ",
    "lastname": "วงษ์มณี",
    "position": "ผบ.พัน.บ.3",
    "province": "ลพบุรี",
    "Email": "chawaaut@hotmail.com",
    "telephone": "0896384367",
    "LineID": "chawaaut",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ภาคภูมิ",
    "lastname": "จันทรักษ์",
    "position": "ผบ.ร.153 พัน.1",
    "province": "ปัตตานี",
    "Email": "Poparmy4051@hotmail.com",
    "telephone": "0619195451",
    "LineID": "Pop4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สมยศ",
    "lastname": "ชูเกษม",
    "position": "ผช.นฝป.ทภ.1",
    "province": "กรุงเทพมหานคร",
    "Email": "general4051@hotmail.com",
    "telephone": "0813513331",
    "LineID": "sc4051",
    "nickname": "",
    "detail": "หนู"
  },
  {
    "rank": "พ.ท.",
    "name": "อาคม ภัทรเตชหิรัญ",
    "lastname": "",
    "position": "ผบ.นฝนศท.มทบ.37",
    "province": "เชียงราย",
    "Email": "Akom0188kt@gmail.com",
    "telephone": "0980879815",
    "LineID": "majorakom",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ไพศาล อุปพรรณ์",
    "lastname": "",
    "position": "ผบ.พัน.นร.กรม นร.รร.ตท.",
    "province": "นครนายก",
    "Email": "",
    "telephone": "0918388892",
    "LineID": "ya4051",
    "nickname": "",
    "detail": "เซี่ยง"
  },
  {
    "rank": "พ.ท.",
    "name": "บัณฑิต",
    "lastname": "เพชรนิล",
    "position": "รอง ผบ.พัน.สพ.ซบร.เขตหลัง",
    "province": "สระบุรี",
    "Email": "Noy4051@hotmail.com",
    "telephone": "0802999952",
    "LineID": "Noy4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "อภิรักษ์",
    "lastname": "วงษ์เพ็ชร์",
    "position": "ผบ.ช.พัน.๕๑",
    "province": "ราชบุรี",
    "Email": "Ohm4051@hotmail.com",
    "telephone": "0921935159",
    "LineID": "Ohmy3111",
    "nickname": "",
    "detail": "ลิงกัง"
  },
  {
    "rank": "พ.อ.",
    "name": "ดิศพันธุ์",
    "lastname": "นาคเสน",
    "position": "หน.ผผภ.กภศ.ผท.ทหาร",
    "province": "กรุงเทพมหานคร",
    "Email": "ohtape@gmail.com",
    "telephone": "0835456195",
    "LineID": "didsaphan",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ณัฎฐ์ธรณ์",
    "lastname": "ปันจุติ",
    "position": "ผช.ผอ.กยก.ทน.3",
    "province": "พิษณุโลก",
    "Email": "lambo.np168@gmail.com",
    "telephone": "0614929554",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วสันต์",
    "lastname": "สุระมณี",
    "position": "ผบ.ส.พัน.23 ทภ.3",
    "province": "พิษณุโลก",
    "Email": "Wasan4051@hotmail.com",
    "telephone": "0815964442",
    "LineID": "",
    "nickname": "",
    "detail": "สิงห์"
  },
  {
    "rank": "พ.ท.",
    "name": "ศราวุธ",
    "lastname": "อินธิชิต",
    "position": "ผบ.นฝ.นศท.มทบ.35",
    "province": "อุตรดิตถ์",
    "Email": "intichit_40@hotmail.com",
    "telephone": "0994956953",
    "LineID": "intichit.9",
    "nickname": "",
    "detail": "เอี่ยว"
  },
  {
    "rank": "พ.ท.",
    "name": "คุณาพงศ์",
    "lastname": "วงศ์จันทรมณี",
    "position": "หน.ฝผค.พล.พัฒนา 3",
    "province": "พิษณุโลก",
    "Email": "gigg.kunapong@gmail.com",
    "telephone": "0894601368",
    "LineID": "giggkunapong",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ชรินทร์",
    "lastname": "สุวรรณะ",
    "position": "ผบ.นฝ.นศท.มทบ.38",
    "province": "น่าน",
    "Email": "pe4051@hotmail.com",
    "telephone": "0894886986",
    "LineID": "pepe4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ศุภชัย",
    "lastname": "ขจัดภัย",
    "position": "รอง ผอ.กอง กบ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "Suppachai4051@gmail.com",
    "telephone": "0871561551",
    "LineID": "Suppachai4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วัชรพงษ์",
    "lastname": "ก้านลำภู",
    "position": "ผบ.พัน.พัฒนา 4",
    "province": "สงขลา",
    "Email": "joke_007@hotmail.com",
    "telephone": "0816262761",
    "LineID": 816262761,
    "nickname": "",
    "detail": "โจ๊ก ขาโก่ง"
  },
  {
    "rank": "พ.อ.",
    "name": "ณฐพล",
    "lastname": "ดังสท้าน",
    "position": "ผช.ผอ.กกฝ.ศตก.",
    "province": "กรุงเทพมหานคร",
    "Email": "na-ta-phon@hotmail.com",
    "telephone": "0817514051",
    "LineID": 866002888,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สโรช",
    "lastname": "สุขศิริ",
    "position": "ผบ.ร.9 พัน.3",
    "province": "กาญจนบุรี",
    "Email": "saroch4051@gmail.com",
    "telephone": "0818573656",
    "LineID": "saroch4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "จักรพงษ์",
    "lastname": "เทพพันธุ์",
    "position": "ผบ.ร.4 พัน 3",
    "province": "พิษณุโลก",
    "Email": "jakrapong4051@gmail.com",
    "telephone": "0819914051",
    "LineID": "jt4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ปรเมธ",
    "lastname": "ศานุพงศ์",
    "position": "ผบ.ร.25 พัน.1",
    "province": "ชุมพร",
    "Email": "poramet4051@gmail.com",
    "telephone": "0895173344",
    "LineID": "sanubhong4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "วิสุทธิ์",
    "lastname": "นวลละออง",
    "position": "ประจำ มทบ.42",
    "province": "สงขลา",
    "Email": "Wisut4051@gmail.com",
    "telephone": "0818982580",
    "LineID": "wkal18252003",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "อินทราวุธ",
    "lastname": "ทองคำ",
    "position": "ผบ.ร.13พัน.2",
    "province": "อุดรธานี",
    "Email": "percius4051@hotmail.com",
    "telephone": "0981799227",
    "LineID": "perzy40",
    "nickname": "",
    "detail": "เป้ ป้าดาว"
  },
  {
    "rank": "พ.ท.",
    "name": "ศันสนะ",
    "lastname": "จักรพันธุ์ ณ อยุธยา",
    "position": "ผบ.ร.21 พัน.1 รอ.",
    "province": "ชลบุรี",
    "Email": "Lucky_834@hotmail.com",
    "telephone": "0819816534",
    "LineID": "sansana40",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ณัฐพงศ์",
    "lastname": "มั่งอะนะ",
    "position": "เสธ.ร.112",
    "province": "ฉะเชิงเทรา",
    "Email": "Nattapong_m311@hotmail.com​",
    "telephone": "0625989790",
    "LineID": "Nattapong4051​",
    "nickname": "",
    "detail": "กันดั้ม"
  },
  {
    "rank": "พ.ท.",
    "name": "ธีระพงศ์",
    "lastname": "สุวรรณเวช",
    "position": "ผบ.ร.19 พัน.2",
    "province": "กาญจนบุรี",
    "Email": "ngew4051@gmail.com",
    "telephone": "0813770823",
    "LineID": "ngew4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "รัชตะ",
    "lastname": "เมฆมณี",
    "position": "อจ.หน.วิขา รร.ส.สส.",
    "province": "กรุงเทพมหานคร",
    "Email": "acdcth@gmail.com",
    "telephone": "0894822880",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "กฤตณ์พัทธ์",
    "lastname": "กรกัน",
    "position": "ผบ.ร.151 พัน.2",
    "province": "นราธิวาส",
    "Email": "kornrakan@hotmail.com",
    "telephone": "0819499669",
    "LineID": "",
    "nickname": "",
    "detail": "งู ตวย"
  },
  {
    "rank": "พ.ท.",
    "name": "อุดมการณ์",
    "lastname": "ศรีแขไตร",
    "position": "ผบ.ร.8 พัน.3",
    "province": "ขอนแก่น",
    "Email": "Domeengine@hotmail.com",
    "telephone": "0905845099",
    "LineID": "Dome405126",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สุทธิชัย",
    "lastname": "รอดแก้ว",
    "position": "ผบ.ปตอ.2 พัน.2",
    "province": "นครราชสีมา",
    "Email": "Suttichai40@gmail.com",
    "telephone": "0969541551",
    "LineID": 933535326,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สุรชาติ",
    "lastname": "อาจหาญ",
    "position": "ผบ.ร.16 พัน.3",
    "province": "ยโสธร",
    "Email": "surachartok@gmail.com",
    "telephone": "0826649594",
    "LineID": "surachartok",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "วัฒนขัย",
    "lastname": "รอสมิง",
    "position": "ประจำ สป.",
    "province": "กรุงเทพมหานคร",
    "Email": "w1980r@hotmail.com",
    "telephone": "0917905551",
    "LineID": "Tonybwin",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สิทธิชัย",
    "lastname": "บำรุงเขต",
    "position": "รอง เสธ.ร.25",
    "province": "สุราษฎร์ธานี",
    "Email": "S_worrawasu@gmail.com",
    "telephone": "0898142513",
    "LineID": "",
    "nickname": "",
    "detail": "ตี๋ คิ้ว พระ"
  },
  {
    "rank": "พ.ท.",
    "name": "วรายุ",
    "lastname": "บุญชัย",
    "position": "ผบ.พัน.นร.รร.ชท.",
    "province": "กรุงเทพมหานคร",
    "Email": "warayu.rtarf@gmail.com",
    "telephone": "0899184051",
    "LineID": "precadet89bp",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ชาตรี",
    "lastname": "พูลมี",
    "position": "ผช.ผอ.กยก.นทพ.",
    "province": "กรุงเทพมหานคร",
    "Email": "chatree.poonmee@gmail.com",
    "telephone": "0946754003",
    "LineID": "poonmee",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ธีรวิทย์ แก้วงามสอง",
    "lastname": "",
    "position": "หน.วิชาการ กวก.ศม. ชรก. กกบ.ศม.",
    "province": "สระบุรี",
    "Email": "teerawit4051@hotmail.com",
    "telephone": "0830484100",
    "LineID": 1426600539,
    "nickname": "",
    "detail": "เมา"
  },
  {
    "rank": "พ.ท.",
    "name": "วิธวินท์",
    "lastname": "วงศ์สรรค์",
    "position": "ผบ.ม.1พัน.17 รอ.",
    "province": "สระบุรี",
    "Email": "pao4051@gmail.com",
    "telephone": "0819099651",
    "LineID": "witawin4051",
    "nickname": "",
    "detail": "เปา"
  },
  {
    "rank": "พ.อ.",
    "name": "สิทธิกร",
    "lastname": "เรืองจิต",
    "position": "รอง ผอ.กอง ยก.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "dett31s@hotmail.com",
    "telephone": "0811416698",
    "LineID": 898903313,
    "nickname": "",
    "detail": "เสล่อ"
  },
  {
    "rank": "พ.ท.",
    "name": "ฉัตร",
    "lastname": "แต่แดงเพชร",
    "position": "รอง ผบ.ศฝ.นศท.มทบ.23",
    "province": "ขอนแก่น",
    "Email": "chatcrma@hotmail.com",
    "telephone": "0898322172",
    "LineID": "chattae4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "นิคม",
    "lastname": "ชุมภู",
    "position": "รอง ผอ.กอง รร.ขว.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "nichumpoo@gmail.com",
    "telephone": "0948726661",
    "LineID": "nikhom4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วรยุทธ",
    "lastname": "บุณยเกียรติ",
    "position": "ผบ.นฝ.นศท.มทบ.43",
    "province": "นครศรีธรรมราช",
    "Email": "Worrayuth.bun@gmail.com",
    "telephone": "0951541191",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "คงกฤช",
    "lastname": "วุฒิสุชีวะ",
    "position": "ผบ.ปตอ.1 พัน.6",
    "province": "กรุงเทพมหานคร",
    "Email": "khongwutti@gmail.com",
    "telephone": "0947955642",
    "LineID": "ed980",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วุฒิชัย",
    "lastname": "ยศพิทักษ์",
    "position": "หน.ฝกร.พล.ร.6",
    "province": "ร้อยเอ็ด",
    "Email": "Woods3chai@hotmail.com",
    "telephone": "0635324789",
    "LineID": "Gam-Gim",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "นที",
    "lastname": "ทองปลิว",
    "position": "ผบ.พัน.ขส.กรม สน.พล.ร.9",
    "province": "กาญจนบุรี",
    "Email": "na.tee.t@hotmail.com",
    "telephone": "0636282558",
    "LineID": "aundamun.thongplew",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "นฤพล",
    "lastname": "วิจิตรโท",
    "position": "ผบ.ร.2 พัน 1 รอ.",
    "province": "ปราจีนบุรี",
    "Email": "Piknaruk@hotmail.com",
    "telephone": "0818899951",
    "LineID": 818899951,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "กวินทร์ณัช",
    "lastname": "เกิดสุข",
    "position": "ผบ.ร.9พัน.2",
    "province": "กาญจนบุรี",
    "Email": "Owl4051@hotmail.com",
    "telephone": "0955326541",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "วัลลภ",
    "lastname": "ตันติวรรธณ์",
    "position": "หน.งบประมาณ ทภ.1",
    "province": "กรุงเทพมหานคร",
    "Email": "wallop_tanbee@hotmail.com",
    "telephone": "0895111740",
    "LineID": "wally_bee",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "โอฬาร",
    "lastname": "ภัทรวุฒิเตโช",
    "position": "รอง หก.กยก.มทบ.32 ชรก.ยก.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "Oran4051@hotmail.com",
    "telephone": "0864042785",
    "LineID": "oran4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "สิริวัฒน์",
    "lastname": "ทัศนานุตริยกุล",
    "position": "รอง ผอ.กบพ.กพ.ทหาร",
    "province": "กรุงเทพมหานคร",
    "Email": "Sitiwat.t@rtarf.mi.th",
    "telephone": "0817050842",
    "LineID": "siboo",
    "nickname": "",
    "detail": "สะบู้"
  },
  {
    "rank": "พ.ท.",
    "name": "เดชชนะ",
    "lastname": "อินทะจักร์",
    "position": "ผบ.ป.1/31 รอ.",
    "province": "ลพบุรี",
    "Email": "Sunse40@gmail.com",
    "telephone": "0835351456",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "กม",
    "lastname": "จารุเศรนี",
    "position": "ผบ.ปตอ.1 พัน.7",
    "province": "กรุงเทพมหานคร",
    "Email": "kom.crma@gmail.com",
    "telephone": "0834446555",
    "LineID": "kom4051",
    "nickname": "",
    "detail": "ด้วง"
  },
  {
    "rank": "พ.อ.",
    "name": "ไชโย",
    "lastname": "เลิศรัตนดำรงกุล",
    "position": "ผช.ผอ.กนผ.สผอ.สส.ทหาร",
    "province": "กรุงเทพมหานคร",
    "Email": "chaiyo.l@rtarf.mi.th",
    "telephone": "0813848011",
    "LineID": "chaiyo4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "วิทยา",
    "lastname": "วงษ์แสงตา",
    "position": "อจ. หน.รร.สพศ.ศสพ.",
    "province": "ลพบุรี",
    "Email": "Eddywittay4051@gmail.com",
    "telephone": "0897804051",
    "LineID": "Falcon_paint",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "นราภัทร",
    "lastname": "วิริยา",
    "position": "หน.เตรียมพล กกพ. กบช.ทม.รอ.",
    "province": "กรุงเทพมหานคร",
    "Email": "Bigbomb_m@yahoo.com",
    "telephone": "0849641515​",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ราชวัติ",
    "lastname": "นิกรกูล",
    "position": "ผบ.ส.พัน.2",
    "province": "ปราจีนบุรี",
    "Email": "",
    "telephone": "0941795222",
    "LineID": "tun40",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ณัฐพล",
    "lastname": "ณีวัง",
    "position": "ผบ.ร.17 พัน.3",
    "province": "เชียงราย",
    "Email": "Nuttha4051@gmail.com",
    "telephone": "0846313364",
    "LineID": "Nuttha51",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "สกล",
    "lastname": "มหาลีวีรัศมี",
    "position": "อจ.หน.จจ.สอ.กศ.รร.ร.ศร.",
    "province": "ประจวบคีรีขันธ์",
    "Email": "Rutsamee4051@hotmail.com",
    "telephone": "0899463171",
    "LineID": "sagon5",
    "nickname": "",
    "detail": "อาเหลียง"
  },
  {
    "rank": "พ.อ.",
    "name": "ธีรชล",
    "lastname": "มหาวรรณ",
    "position": "หก.กบ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "bo.x@windowslive.com",
    "telephone": "0991936595",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ณัฐ",
    "lastname": "พุ่มหรดี",
    "position": "รอง ผบ.ทรว.รอ.พัน.2",
    "province": "กรุงเทพมหานคร",
    "Email": "natphum51@gmail.com",
    "telephone": "0911955553",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "กฤษณ์",
    "lastname": "แสงกล้า",
    "position": "หน.ฝกม.พล.ร.7",
    "province": "เชียงใหม่",
    "Email": "krit.redhat@gmail.com",
    "telephone": "0945944042",
    "LineID": "kritredhat4051",
    "nickname": "",
    "detail": "เข้"
  },
  {
    "rank": "พ.ท.",
    "name": "อุเทน",
    "lastname": "จีนทองหลาง",
    "position": "ผบ.ร.8 พัน.2",
    "province": "ขอนแก่น",
    "Email": "Uthen4051@hotmail.com",
    "telephone": "0810596566",
    "LineID": "uthen4051",
    "nickname": "",
    "detail": "เทน"
  },
  {
    "rank": "พ.ท.",
    "name": "เกียรติภูมิ",
    "lastname": "มินทระ",
    "position": "ผบ.นฝ.นศท.มทบ.28",
    "province": "เลย",
    "Email": "kminthara4051@gmail.com",
    "telephone": "0982620626",
    "LineID": "minthara4051",
    "nickname": "",
    "detail": "เอ๋"
  },
  {
    "rank": "พ.ท.",
    "name": "สุรศักร",
    "lastname": "ทั่วด้าว",
    "position": "ผบ.ร.15 พัน.2",
    "province": "นครศรีธรรมราช",
    "Email": "Toadown@gmail.com",
    "telephone": "0818940089",
    "LineID": "Toadown110622",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ศักดิ์นรินทร์",
    "lastname": "อัชวนันท์",
    "position": "ผบ.ม.พัน.9 พล.ร.4",
    "province": "พิษณุโลก",
    "Email": "intakaew11@gmail.com",
    "telephone": "0819633937",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "รุ่งโรจน์",
    "lastname": "เปล่งสันเทียะ",
    "position": "ผบ.ม.3 พัน.26",
    "province": "เพชรบูรณ์",
    "Email": "kitesuan@gmail.com",
    "telephone": "0992465051",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ภาณุเดช",
    "lastname": "บุญประสิทธิ์",
    "position": "ทส.รมว.กห.",
    "province": "กรุงเทพมหานคร",
    "Email": "panudech4051@hotmail.com",
    "telephone": "0852362345",
    "LineID": "tump40",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "ร.ท.",
    "name": "ราขศักดิ์",
    "lastname": "จั่นเงิน",
    "position": "",
    "province": "กรุงเทพมหานคร",
    "Email": "",
    "telephone": "0864156225",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "ประสบโชค",
    "lastname": "อรัณยกานนท์",
    "position": "หน.ฝ.สรรพกำลัง",
    "province": "กาญจนบุรี",
    "Email": "bankcyber9981@gmail.com",
    "telephone": "0908970589",
    "LineID": "Ouiikho",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ภัทราวุธ",
    "lastname": "หาญมนตรี",
    "position": "รอง.ผบ.ทพ.41",
    "province": "ยะลา",
    "Email": "",
    "telephone": "0985355823​",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "จตุพล",
    "lastname": "ศรีเกตุ",
    "position": "ผบ.ร.152 พัน.2",
    "province": "ยะลา",
    "Email": "jatupol19@gmail.com",
    "telephone": "0986713055",
    "LineID": "จตุพล",
    "nickname": "",
    "detail": "จ๊ะ"
  },
  {
    "rank": "พ.ท.",
    "name": "ประสิทธิ์",
    "lastname": "สุวรรณรัตน์",
    "position": "หน.ฝกร.พล.พัฒนา4",
    "province": "สงขลา",
    "Email": "prasith_suwa@hotmail.com",
    "telephone": "0897324053",
    "LineID": "sith.ii",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ศุภชัย",
    "lastname": "สองทวี",
    "position": "ผช.ฝอ.5 ทภ.4",
    "province": "นครศรีธรรมราช",
    "Email": "",
    "telephone": "0982255369",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ธนวัฒน์​",
    "lastname": "สายสกุลรัตน์",
    "position": "รอง.ผบ.ทพ.49",
    "province": "นราธิวาส",
    "Email": "",
    "telephone": "0890450559",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วีระชาติ",
    "lastname": "โชติวรอานนท์",
    "position": "ผบ.พัน.พัฒนา ๓",
    "province": "เชียงใหม่",
    "Email": "Weerachat4051@hotmail.com",
    "telephone": "0813819191",
    "LineID": 813819191,
    "nickname": "",
    "detail": "กิ่ง"
  },
  {
    "rank": "พ.ท.",
    "name": "อัดชา",
    "lastname": "ทานาค",
    "position": "หน. ผผค. กรซย.ศซส. สพ. ทบ.",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0897825077",
    "LineID": 897825077,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วรพันธ์",
    "lastname": "ทรัพย์ยั่งยืนกุล",
    "position": "ผบ.ร.2 พัน.3 รอ.",
    "province": "ปราจีนบุรี",
    "Email": "Worapan4051@hotmail.com",
    "telephone": "0814283003",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ปรีชา",
    "lastname": "วงศ์สาขา",
    "position": "ผบ.ม.3 พัน.13",
    "province": "เพชรบูรณ์",
    "Email": "",
    "telephone": "",
    "LineID": "4051wongsakha",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "เอกมล",
    "lastname": "นาลาพงษ์",
    "position": "ผบ.ส,พัน,",
    "province": "กรุงเทพมหานคร",
    "Email": "",
    "telephone": "",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "สุริวัชร์",
    "lastname": "อัครพรเดชาพงษ์",
    "position": "ผบ.ม.7 พัน.8",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0942567899",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ณัฏฐพล",
    "lastname": "สุนทรนนท์",
    "position": "รอง ผบ.กรม ทพ.43",
    "province": "ปัตตานี",
    "Email": "s2baink@gmail.com",
    "telephone": "0822224246",
    "LineID": 822224246,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "นพดล",
    "lastname": "พรหมมาก",
    "position": "ผบ.ร.153 พัน.3",
    "province": "ปัตตานี",
    "Email": "-",
    "telephone": "0892358350",
    "LineID": 892358350,
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "อนุชา",
    "lastname": "ดาวังปา",
    "position": "ผบ.ป.6พัน.6",
    "province": "อุบลราชธานี",
    "Email": "Aunko2327@gmail.com",
    "telephone": "0842649669",
    "LineID": "Anucha4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "สราวุฒิ",
    "lastname": "คงรอด",
    "position": "รอง ผอ.กอง สวพ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "sarawut_kongrod@hotmail.com",
    "telephone": "0843620351",
    "LineID": "sarawut_1",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ทรงพล",
    "lastname": "บุณยะวิโรจ",
    "position": "ผบ.รพศ.4 พัน.2",
    "province": "พิษณุโลก",
    "Email": "aey4051@hotmail.com",
    "telephone": "0942615955",
    "LineID": 942615955,
    "nickname": "",
    "detail": "นุ้ย"
  },
  {
    "rank": "พ.ท.",
    "name": "เกรียงไกร",
    "lastname": "แก้วกระจาย",
    "position": "ผบ.ม.5 พัน.20 รอ.",
    "province": "สระบุรี",
    "Email": "kngyooth@gmail.com",
    "telephone": "0936155663",
    "LineID": "superman4051",
    "nickname": "",
    "detail": "แหวง"
  },
  {
    "rank": "พ.ท.",
    "name": "สาคริน",
    "lastname": "ปิยะกุล",
    "position": "ผช.ฝยก.ทภ.๒",
    "province": "นครราชสีมา",
    "Email": "",
    "telephone": "0914539997",
    "LineID": "",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ถานัน",
    "lastname": "นันตา",
    "position": "ผบ.พัน.บ.2",
    "province": "ลพบุรี",
    "Email": "thananlovepu@gmail.com",
    "telephone": "0815719863",
    "LineID": "",
    "nickname": "",
    "detail": "นักมวย"
  },
  {
    "rank": "พ.อ.",
    "name": "ศราวุธ",
    "lastname": "ไชยวิเศษ",
    "position": "ผช.ผอ.กคก.สบท.สปช.ทหาร.บก.ทท.",
    "province": "กรุงเทพมหานคร",
    "Email": "thaistar3@hotmail.com",
    "telephone": "0987945428",
    "LineID": "chaiwiset142",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ธนากร",
    "lastname": "คงขำ",
    "position": "หน.ประสานงานพิธีการ กลก.สร.",
    "province": "กรุงเทพมหานคร",
    "Email": "911.tko@gmai.com",
    "telephone": "0816888861",
    "LineID": "911-lism",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.อ.",
    "name": "สุรศักดิ์",
    "lastname": "พบวันดี",
    "position": "ผบ.พัน.ขกท.",
    "province": "กรุงเทพมหานคร",
    "Email": "popwandee@gmail.com",
    "telephone": "0867800091",
    "LineID": "spopwandee",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "อัฐฏวัฒน์",
    "lastname": "ตัณกุลรัตน์",
    "position": "นอกราชการ",
    "province": "ลพบุรี",
    "Email": "lakchaipotijuk5@hotmail.com",
    "telephone": "0992599651",
    "LineID": "Numza4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "เอกชัย",
    "lastname": "สุขพิมาย",
    "position": "หน.ผฝศ.กยข.สพ.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "outofgravity@gmail.com",
    "telephone": "0897074773",
    "LineID": "outofgravity 4051",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ประสิทธิ์ สุวรรณรัตน์",
    "lastname": "",
    "position": "หน.ฝกร.พล.พัฒนา4",
    "province": "สงขลา",
    "Email": "prasith_suwa@hotmail.com",
    "telephone": "0897324053",
    "LineID": "sith.ii",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ประสิทธิ์ สุวรรณรัตน์",
    "lastname": "",
    "position": "หน.ฝกร.พล.พัฒนา4",
    "province": "สงขลา",
    "Email": "prasith_suwa@hotmail.com",
    "telephone": "0897324053",
    "LineID": "sith.ii",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "ยศวีร์",
    "lastname": "คงธนจารุอนันต์",
    "position": "ผบ.ปตอ.1 พัน.3",
    "province": "ลพบุรี",
    "Email": "yoswee4051@gmail.com",
    "telephone": "0873735151",
    "LineID": "Yoswee9256",
    "nickname": "",
    "detail": "คิงคอง"
  },
  {
    "rank": "พ.ท.",
    "name": "จิรชัย",
    "lastname": "ชูช่วย",
    "position": "รองเสธ.ร.9",
    "province": "กาญจนบุรี",
    "Email": "",
    "telephone": "0818151540",
    "LineID": "",
    "nickname": "",
    "detail": "ห้อย"
  },
  {
    "rank": "พ.อ.",
    "name": "ปรัชญา",
    "lastname": "คุ้มฉายา",
    "position": "เสธ.ช.11",
    "province": "ราชบุรี",
    "Email": "amp4051@gmail.com",
    "telephone": "0955131008",
    "LineID": "amp4051",
    "nickname": "",
    "detail": "เดิ้ง"
  },
  {
    "rank": "พ.ท.",
    "name": "ปัญจรุจน์",
    "lastname": "ธิติอัคราเกียรติ",
    "position": "ผบ.ม.พัน.22 ศม.",
    "province": "สระบุรี",
    "Email": "Punjaruj4051@gmail.com",
    "telephone": "0995914935",
    "LineID": "Golfleng",
    "nickname": "",
    "detail": ""
  },
  {
    "rank": "พ.ท.",
    "name": "วันจักร ช่วยบำรุง",
    "lastname": "",
    "position": "ผบ.รพศ.4 พัน.1",
    "province": "พิษณุโลก",
    "Email": "wanjak_crma51@hotmail.com",
    "telephone": "0895559555",
    "LineID": 895559555,
    "nickname": "",
    "detail": "หมึก"
  },
  {
    "rank": "พ.อ.",
    "name": "เอกพงษ์",
    "lastname": "กฤตยาเกียรติชุติ",
    "position": "ผบ.กรม ทพ.12",
    "province": "สระแก้ว",
    "Email": "Ake_e46@hotmail.com",
    "telephone": "0816995363",
    "LineID": "Cavalry4051",
    "nickname": "",
    "detail": "เอก โคปา"
  },
  {
    "rank": "พ.ท.",
    "name": "พงษ์เทพ",
    "lastname": "แตงพลับ",
    "position": "ผบ.ร.5 พัน.3",
    "province": "สงขลา",
    "Email": "Pongtep@gmail.com",
    "telephone": "0635499799",
    "LineID": "dangnoy4051",
    "nickname": "",
    "detail": "แมงวัน แดง"
  },
  {
    "rank": "พ.ต.",
    "name": "สฤษฎิ์ศิริ",
    "lastname": "ศิริเลิศ",
    "position": "ประจำ มอบ.43",
    "province": "นครศรีธรรมราช",
    "Email": "",
    "telephone": "0831871100",
    "LineID": "Champ594051",
    "nickname": "",
    "detail": "แชมป์ หนิม สนิม"
  },
  {
    "rank": "พ.อ.",
    "name": "สฤษดิ์",
    "lastname": "ลาวัณย์วิสุทธิ์",
    "position": "สก.ทบ.",
    "province": "กรุงเทพมหานคร",
    "Email": "",
    "telephone": "0618994159",
    "LineID": "",
    "nickname": "",
    "detail": "ซิน ส่วนกลาง"
  }';

$coupon = new RestDB();
$returnValue = $coupon->insertDocument($collectionName,$obj);

        if($returnValue){
		          $message= "<div align='center' class='alert alert-success'>บันทึกข้อมูล ".$name." เรียบร้อย</div>";
		         echo $message;
	        }else{
		   $message= "<div align='center' class='alert alert-danger'>ไม่สามารถบันทึกได้</div>";
		         echo $message;
                 }
			$_SESSION["message"]=$message;


}  // end of if(isset($_POST['coupon_id'])&&isset($_POST['name']))

?>

    </div> <!-- end .container -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>
